### ISSUE TITLE
VkResult: ErrorDeviceLost in NeoDemo

### ISSUE THREAD

**Issue by vpenades** [mellinoe/veldrid#157]
I've just ran the latest version of NeoDemo and got this exception:

Unsuccessful VkResult: ErrorDeviceLost.

   ```
at Veldrid.Vk.VulkanUtil.CheckResult(VkResult result) in F:\Github\Mellinoe-Veldrid\src\Veldrid\Vk\VulkanUtil.cs:line 20
   at Veldrid.Vk.VkGraphicsDevice.SubmitCommandBuffer(VkCommandList vkCL, VkCommandBuffer vkCB, UInt32 waitSemaphoreCount, VkSemaphore* waitSemaphoresPtr, UInt32 signalSemaphoreCount, VkSemaphore* signalSemaphoresPtr, Fence fence) in F:\Github\Mellinoe-Veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 221
   at Veldrid.Vk.VkGraphicsDevice.SubmitCommandList(CommandList cl, UInt32 waitSemaphoreCount, VkSemaphore* waitSemaphoresPtr, UInt32 signalSemaphoreCount, VkSemaphore* signalSemaphoresPtr, Fence fence) in F:\Github\Mellinoe-Veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 179
   at Veldrid.Vk.VkGraphicsDevice.SubmitCommandsCore(CommandList cl, Fence fence) in F:\Github\Mellinoe-Veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 164
   at Veldrid.GraphicsDevice.SubmitCommands(CommandList commandList) in F:\Github\Mellinoe-Veldrid\src\Veldrid\GraphicsDevice.cs:line 105
   at Veldrid.NeoDemo.Scene.RenderAllSingleThread(GraphicsDevice gd, CommandList cl, SceneContext sc) in F:\Github\Mellinoe-Veldrid\src\NeoDemo\Scene.cs:line 238
   at Veldrid.NeoDemo.Scene.RenderAllStages(GraphicsDevice gd, CommandList cl, SceneContext sc) in F:\Github\Mellinoe-Veldrid\src\NeoDemo\Scene.cs:line 87
   at Veldrid.NeoDemo.NeoDemo.Draw() in F:\Github\Mellinoe-Veldrid\src\NeoDemo\NeoDemo.cs:line 568
   at Veldrid.NeoDemo.NeoDemo.Run() in F:\Github\Mellinoe-Veldrid\src\NeoDemo\NeoDemo.cs:line 236
   at Veldrid.NeoDemo.Program.Main(String[] args) in F:\Github\Mellinoe-Veldrid\src\NeoDemo\Program.cs:line 9
```

Also, and unrelated to this, the code of Camera.cs assumes I have a game controller, and crashes because _controller is null.

**Comment by SomeAnon42** [comment]
Yeah, this issue has been there since... well, I can't even remember. Maybe we should try git bisecting the "bad" commit.

**Comment by vpenades** [comment]
@SomeAnon42 I have a GeForce GTX 750 Ti

So, what is causing this issue?

**Comment by mellinoe** [comment]
@vpenades Sorry that you hit this. I'm assuming that this is a new issue which you weren't experiencing previously? If so, it would be good to figure out at what point this started ocurring. Also, are you able to run any of the other sample projects (e.g. in https://github.com/mellinoe/veldrid-samples) with the Vulkan backend, ones which are potentially less demanding? Alternatively, I'd be interested in hearing if commenting out [this line]() fixes anything -- doing so skips loading all of the sponza meshes and textures.

**Comment by mellinoe** [comment]
If you haven't already, I'd appreciate if you could install the Vulkan SDK to get better debug information -- it could help identify any problems (although the validation layers don't catch everything).

**Comment by vpenades** [comment]
@mellinoe I run NeoDemo from time to time, maybe once every one or two months. So yes, this is something that's been added in the last two months or so...

Removing AddSponzaAtriumObjects line makes the NeoDemo to work correctly, with just a nice skybox.

All the Veldrid-Samples work correcly... it seems the only one affected is NeoDemo.

I'll try installing the vulkan sdk when I have a moment....

**Comment by vpenades** [comment]
@mellinoe which is the process to launch neodemo with the vulkan sdk?

**Comment by mellinoe** [comment]
@vpenades If the SDK is installed, debug features will automatically be enabled by Veldrid. [This line](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/Vk/VkGraphicsDevice.cs#L601) should be reached and print something to the debug output.

**Comment by vpenades** [comment]
@mellinoe No luck, [the line you commented](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/Vk/VkGraphicsDevice.cs#L601) is indeed called, but the callback is not.

The only additional hint I can give you is where is happening:

```c#
        lock (_graphicsQueueLock)
            {
                VkResult result = vkQueueSubmit(_graphicsQueue, 1, ref si, vkFence);
                CheckResult(result);    // << this is the one that's failing
                if (useExtraFence)
                {
                    result = vkQueueSubmit(_graphicsQueue, 0, null, submissionFence);
                    CheckResult(result);
                }
            }
```

**Comment by mellinoe** [comment]
I pushed a branch that reverted the largest most recent Vulkan-related change. Could you pull that branch down and see if it has any effect? The branch is called `revert-image-layout-fix`.

**Comment by vpenades** [comment]
I've just did, it still crashes.

Then, I've began pulling older revisions from Master, to try to pinpoint where the breaking change happened....

... And at some point I realized NeoDemo was working for me before because the default graphics context being used was DirectX11, not Vulkan... when running NeoDemo I really didn't care about which graphics backend was being used at a given time.

So either the problem was introduced a while ago, or it is some sort of glitch in my graphics card.

I'm thinking on more ways of checking what's wrong.... but it is also weird that only NeoDemo is affected, and all other examples work correctly.

**Comment by vpenades** [comment]
Latest findings (with Master)
- Direct3D11 backend works at 90fps
- OpenGL backend works at 20fps
- Whenever vulkan crashes the graphics card, all graphics backends fail afterwards, I have to reboot to recover; this is seriously slowing down my tests,

I tried to load parts of Atrium scene to see if it had an effect:
- Skipping the whole atrium model works
- Skipping the textures, and loading the models untextured fails.
- Loading just the first submesh of Atrium, untextured, works.

This led me to think there might be an issue with the submeshes, so I've began loading more and more submeshes, and it kept working until I loaded the first 9 meshes of the scene, so I thought the mesh 8 might be the issue.... but then, loading it alone didn't fail

**Comment by mellinoe** [comment]
@vpenades Thanks for doing all of those tests, more information is always helpful.

I do have a GTX 770 lying around which should be close enough to give more information, but I will need to set aside some time to really sit down to debug through this if it's not going to be something the validation layers want to help with.

**Comment by mellinoe** [comment]
I don't understand why yet, but using a R16_UNorm depth buffer instead of R32_Float fixes it on my GTX 770:

https://github.com/mellinoe/veldrid/blob/master/src/NeoDemo/SceneContext.cs#L216

In any case, none of this should be destabilizing the entire system, so there is very likely some sort of driver bug that's only affecting the 700-series of cards.

**Comment by vpenades** [comment]
I guess at some point you'll need a profile based graphics capabilities filter,  with known limitations of specific cards and driver versions. I believe most major graphics engines do something like that.

Theoretically, graphics drivers should be bug free since they're one of the most critical systems in a computer, but when dealing with bleeding edge graphics, it's obvious it's not the case.

So, let's say you detect a specific graphics card with a known bug that's not fixed below a certain driver version, you can either throw an early exception, or limit the exposed capabilities to the graphics backend to ensure the offending feature cannot be selected.

In this particular case, if you detect a GTX 7xx you could remove R32_Float from the list of valid formats for depth buffer. If at some point it is fixed, you can allow it again if the driver fixing the issue is found.

**Comment by mellinoe** [comment]
I've certainly thought about that in the past, and I agree that in the ideal world, some sort of device filtering would be in Veldrid itself. Realistically, that's very hard for me to maintain by myself, and not only because I don't have enough different types of GPUs to test things on. Even in this case, it's not clear that using a 32-bit float depth buffer is broken, because that format does work in other Framebuffers that I've tested. There's something very particular about the way it's used in NeoDemo that triggers the issue. If we were able to actually nail down precisely when it breaks (and could write a test case verifying it), then handling it that way could make sense.

**Comment by vpenades** [comment]
It's something you're not supposed to do alone... I don't know how much Veldrid is being used already in commercial products, but when you hit the big market,  you'll be flooded with issues and complaints.

I work with depth sensors, they're a pain to work with; USB compatibility issues, graphics computing issues... In many cases, we discovered that some issues were related to the energy saving settings, which is something end users can change at any time...  and laptops are pure evil.

But in the end, our customers won't recognize the problems are caused by their computers... They paid for a product, the product is not behaving as expected, so they ask for a refund.

Indeed, it's impossible for us to test all the hardware in the wild, so we created a two step solution:

- A logging API that dumps system information when there's an issue. We automated the whole thing so when a client complains, the client can send the log with a single click.
- when we receive enough complaints on a specific hardware, we add it to a table, so when our software runs, it displays a warning if conflicting software or setup  is found.

This didn't solve the hardware issues, but it helped saving a lot of time when we get a new complaint, and in many cases, our customers are satisfied with a much faster reply.

Think that not everybody updates their graphics drivers often, I have to manually update them because I refuse to install the nvidia GeForce experience spyware, but at some point, you can get issues from people using seriously outdated drivers. Did, just checking for at least a specific driver version might help reducing the number of issues.

Call it preemptive measures 😉

**Comment by mellinoe** [comment]
I don't disagree with any of that; users of Veldrid don't care where a problem originates, and they want things to work automatically. After all, that's why they're not using Vulkan/Metal/D3D/GL directly. But again, that's very (prohibitively) expensive for me to maintain on an ongoing basis. Although it is common for games and larger engines to do blacklisting, I'm not aware of other low-level graphics libraries that maintain blacklists (I could be wrong), most likely because it's very difficult.

I don't want to derail this current issue too much, because I still haven't definitively established why this problem is occurring. I'm aware of some validation layer warnings (not errors) that occur in a couple of scenarios, which could be addressed. My best guess is that this is caused by some memory corruption in the driver. Changing how Texture and DeviceBuffer memory is allocated in Vulkan (an area with a lot of room for improvement anyways) could fix this problem indirectly, while eliminating some validation warnings. That's one thing I've been hoping to implement for a while, so I will try to bump up the priority of it.
