### ISSUE TITLE
[D3D11] Very heavy allocations during rendering

### ISSUE THREAD

**Issue by Doom2fan** [mellinoe/veldrid#301]
After the switch to using Vortice instead of SharpDX, a lot more allocations have popped up.
All of these allocations were in about 9 seconds:
![image](https://user-images.githubusercontent.com/1653873/91326418-b3752480-e79a-11ea-9fe9-d5f646b4a699.png)
![image](https://user-images.githubusercontent.com/1653873/91325918-1e722b80-e79a-11ea-9ec4-f825fa958a49.png)

**Comment by amerkoleci** [comment]
This is quite strange, Vortice doesn't have different way of allocating objects or disposing, can you digg and provide more info please? If it is an issue on vortice side I will gladly fix it.

**Comment by mellinoe** [comment]
Most of this was happening because a `params ID3D11Buffer[]` overload of `PSSetConstantBuffers` was being used (by the way @amerkoleci, there is some naming inconsistency between those overloads that made it a little confusing to discover, see https://github.com/amerkoleci/Vortice.Windows/issues/84).

https://github.com/mellinoe/veldrid/commit/c8f2a4d9382d549b8c7c7a0bdd8b5aad0a7cff94

I'm gathering another memory profile now, but it's taking quite a long time on my machine currently. I suspect that the ID3D11CommandList and UnorderedAccessView allocations are caused by something else.

**Comment by amerkoleci** [comment]
Remember that you can reuse the ID3D11CommandList  in ExecuteCommandList

**Comment by mellinoe** [comment]
@amerkoleci Is this the expected way to re-use the ID3D11CommandList?

```C#
            if (DeviceCommandList == null)
            {
                DeviceCommandList = _context.FinishCommandList(false);
            }
            else
            {
                _context.FinishCommandList(false, DeviceCommandList);
            }
```

**Comment by amerkoleci** [comment]
@mellinoe yeah, it replaces the NativeHandle with the second overload.

**Comment by mellinoe** [comment]
I pushed another change that avoids ID3D11CommandList allocations, and from my profiling everything is clean.

**Comment by Doom2fan** [comment]
I'm still getting some allocations here. Both from setting compute resource sets, with uniform and structured buffers (no idea if it happens with other type of resources, as I don't use them in compute shaders yet
I'll try to find what line the allocations are in.

**Comment by amerkoleci** [comment]
@mellinoe you can update to 1.8.3 version where all names should be fixed

**Comment by Doom2fan** [comment]
This fixes some of it, but the ones caused by the `params` functions still happen. Updating to 1.8.3 and using the new function names fixes it. There's also some array allocations caused by these lines:
[1](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/D3D11/D3D11CommandList.cs#L1026)
[2](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/D3D11/D3D11CommandList.cs#L1056)

**Comment by amerkoleci** [comment]
Hi @Doom2fan, PR #302 fixes all the allocation stuff.
